### ISSUE TITLE
RatePlans endpoint not wokring - 500 status code

### ISSUE THREAD

**Issue by vbledar** [windingtree/wt-read-api#150]
RatePlans endpoint is not working for both playground and demo.

URL: [https://playground-api.windingtree.com/hotels/0x50034977Cb8B3ca62b8CCbE87fcD32Ff9170B782/roomTypes/single-room/ratePlans](url)

`{
"status": 500,
"code": "#genericError",
"short": "Something went wrong.",
"long": "Something went wrong. Please contact the administrator."
}`

**Comment by JirkaChadima** [comment]
This was a momentary issue related to inaccessible swarm stored data (as can be seen below in the logs). However, the reported 500 error is wrong, it should respond with a more sensible message. We'll look into it.

Right now, I'm able to access the data through API.

```

09/01 02:27 PM (1d)
error: e: Cannot download data: Error 404.
09/01 02:27 PM (1d)
    at t.<anonymous> (/usr/src/app/node_modules/@windingtree/wt-js-libs/dist/node/wt-js-libs.js:1:40830)
09/01 02:27 PM (1d)
    at tryCatch (/usr/src/app/node_modules/regenerator-runtime/runtime.js:62:40)
09/01 02:27 PM (1d)
    at Generator.invoke [as _invoke] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:296:22)
09/01 02:27 PM (1d)
    at Generator.prototype.(anonymous function) [as throw] (/usr/src/app/node_modules/regenerator-runtime/runtime.js:114:21)
09/01 02:27 PM (1d)
    at step (/usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
09/01 02:27 PM (1d)
    at /usr/src/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
09/01 02:27 PM (1d)
    at process._tickCallback (internal/process/next_tick.js:68:7)
09/01 02:27 PM (1d)
info: ::ffff:172.29.0.3 - [01/Sep/2018:12:27:46 +0000] GET /hotels/0x50034977Cb8B3ca62b8CCbE87fcD32Ff9170B782/roomTypes/single-room/ratePlans HTTP/1.1 500 134 - 33368.876 ms
```

**Comment by vbledar** [comment]
I see also that it is working for the playground endpoint. The same issue probably is happening on the demo endpoint.
